# Generated by Django 2.1 on 2018-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('keio1', models.CharField(max_length=100)),
                ('keio2', models.CharField(max_length=100)),
                ('e1', models.CharField(max_length=100)),
                ('e2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('position', models.IntegerField()),
                ('playername', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('before', models.IntegerField()),
                ('course', models.IntegerField()),
            ],
        ),
    ]
